### ISSUE TITLE
Trouble getting the bot to start.

### ISSUE THREAD

**Issue by diydavindra** [sugi-chan/Pendragon_Alter#1]
I have installed all the packages required for the bot but it spits out this, im not too sure what to make of it.
Traceback (most recent call last):
  File "C:\Users\Dave\Desktop\Pendragon_Alter-master\pendragon_alter.py", line 94, in <module>
    main()
  File "C:\Users\Dave\Desktop\Pendragon_Alter-master\pendragon_alter.py", line 35, in main
    turn_start = detect_start_turn()
  File "C:\Users\Dave\Desktop\Pendragon_Alter-master\utils.py", line 302, in detect_start_turn
    attack_model.load_state_dict(torch.load('models/attack_resnet18.pth'))
  File "C:\Users\Dave\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\serialization.py", line 365, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'models/attack_resnet18.pth'

**Comment by diydavindra** [comment]
Also running main gives this output.
Traceback (most recent call last):
  File "C:\Users\Dave\Desktop\Pendragon_Alter-master\main.py", line 1, in <module>
    from colosseum import Battle
  File "C:\Users\Dave\Desktop\Pendragon_Alter-master\colosseum.py", line 404
    turning off this section for testing
              ^
SyntaxError: invalid syntax
